language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
  - nvm install stable
  - npm install netlify-cli -g
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${TRAVIS_COMMIT_MESSAGE:0:70}"

env:
  - NETLIFY_SITE_ID=8d3ac697-172f-4abe-9caf-09a4e81b9d42
  # NETLIFY_AUTH_TOKEN set in travis settings

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
      
after_success:
- curl -X POST -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" -d "{}" "https://api.netlify.com/api/v1/deploys/${temp##*|}/lock"